// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zykrnkagkhkncibuxclp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5a3Jua2Fna2hrbmNpYnV4Y2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTg5MjAsImV4cCI6MjA3NTE3NDkyMH0.t5Ucp4ye8wH33J3estE1U2l7EDaa9qGRAs69kz9PB_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});